server:
  port: 3001
spring:
  application:
    name: parent-zuul
#  redis:
#    host: 39.100.8.62
#    port: 6379
#    password:
#    jedis:
#      pool:
#        max-active: 8
#        max-wait: -1
#        max-idle: 500
#        min-idle: 0
#    lettuce:
#      shutdown-timeout: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:3000/eureka/
    ##开启健康检查（需要spring-boot-starter-actuator依赖）
  #    ealthcheck:
  #      enabled: true
  instance:
    ##租期到期时间（默认90秒）不怕出错的话，时间可以更短
    lease-expiration-duration-in-seconds: 90
    ##租期更新时间间隔（默认30秒）
    lease-renewal-interval-in-seconds: 30

zuul:
  routes:
    project1:
      path: /project1/**
      serviceId: parent-project1
  sensitive-headers:
    - Cookie,Set-Cookie,Authorization

##屏蔽安全验证
management:
  endpoints:
    web:
      exposure:
        include: "*"
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 3000


